# -*- coding: utf-8 -*-
# nanomsg nanocat building script
#

import time
Import('genv')

env = Environment()
env["CC"] = genv["CC"]
env["CXX"] = genv["CXX"]
env["AS"] = genv["AS"]
env["AR"] = genv["AR"]
env["LINK"] = genv["LINK"]
env["OBJCOPY"] = genv["OBJCOPY"]
env["NM"] = genv["NM"]
env["ENV"] = genv["ENV"]

env["CFLAGS"] += [
]

env["LIBPATH"] = [
    genv["out"],
]

env["CCFLAGS"] = [
    "-O3",
    "-g",
    "-Wno-unused-value",
    "-Wno-unused-parameter",
]

env["LINKFLAGS"] = [
]

inc = [
    "#tests",
    ".",
]

srcs = [
    "block.c",
    "device5.c",
    "emfile.c",
    "ipc.c",
    "pair.c", 
    "shutdown.c",
    "tcp.c",
    "trie.c",
    "bug328.c",
    "device6.c",
    "hash.c",
    "ipc_shutdown.c",
    "pipeline.c",
    "reqrep.c",
    "stats.c",
    "tcp_shutdown.c",
    "bus.c",
    "device7.c",
    "inproc.c",
    "ipc_stress.c",
    "poll.c",
    "reqttl.c",
    "survey.c",
    "term.c",
    "cmsg.c",
    "device.c",
    "inproc_shutdown.c",
    "list.c",
    "prio.c",
    "surveyttl.c",
    #"win_sec_attr.c",
    #"ws.c",
    #"ws_async_shutdown.c",
]

lib = [
    "nanomsg",
    "pthread",
]

test_progs = []

for src in srcs:
    prog = env.Program(source=src, LIBS=lib, CPPPATH=inc)
    test_progs += [prog]
Return("test_progs")
