# -*- coding: utf-8 -*-
# lib building script
#

Import('genv')

lib_files = []

# libuv script
uv_script = 'SConscript.uv'
uv_files = genv.SConscript(uv_script)
genv.Install(genv["out"], uv_files)

# extra script
extra_script = 'SConscript.extra'
extra_files = genv.SConscript(extra_script)
genv.Install(genv["out"], extra_files)
