# -*- coding: utf-8 -*-
# unqlite building script
#

import os

Import('genv')

env = Environment()
env["CC"] = genv["CC"]
env["CXX"] = genv["CXX"]
env["AS"] = genv["AS"]
env["AR"] = genv["AR"]
env["LINK"] = genv["LINK"]
env["OBJCOPY"] = genv["OBJCOPY"]
env["NM"] = genv["NM"]
env["ENV"] = genv["ENV"]
env["BUILD_PLATFORM"] = genv["BUILD_PLATFORM"]

env["CCFLAGS"] = ["-DUNQLITE_ENABLE_THREADS"]

dst = "unqlite"

inc = [
    ".",
]

src = [
    "unqlite.c",
]

lib = []

unqlite_static = env.StaticLibrary(target=dst, source=src, LIBS=lib, CPPPATH=inc)
Return("unqlite_static")
