# -*- coding: utf-8 -*-
# nanomsg demo building script
#

import time
Import('genv')

env = Environment()
env["CC"] = genv["CC"]
env["CXX"] = genv["CXX"]
env["AS"] = genv["AS"]
env["AR"] = genv["AR"]
env["LINK"] = genv["LINK"]
env["OBJCOPY"] = genv["OBJCOPY"]
env["NM"] = genv["NM"]
env["ENV"] = genv["ENV"]

env["CFLAGS"] += [
]

env["LIBPATH"] = [
    genv["out"],
]

env["CCFLAGS"] = [
    "-O3",
    "-g",
    "-Wno-unused-value",
    "-Wno-unused-parameter",
]

env["LINKFLAGS"] = [
]

inc = [
    genv["include"],
    ".",
    "../src",
]

srcs = [
    "async_demo.c",
    "pthread_demo.c",
    "pubsub_demo.c",
    "rpc_demo.c",
]

lib = [
    "nanomsg",
    "pthread",
]

demo_progs = []

for src in srcs:
    prog = env.Program(source=src, LIBS=lib, CPPPATH=inc)
    demo_progs += [prog]
Return("demo_progs")
