# -*- coding: utf-8 -*-
# tests building script
#

import time
Import('genv')

env = Environment()
env["CC"] = genv["CC"]
env["CXX"] = genv["CXX"]
env["AS"] = genv["AS"]
env["AR"] = genv["AR"]
env["LINK"] = genv["LINK"]
env["OBJCOPY"] = genv["OBJCOPY"]
env["NM"] = genv["NM"]
env["ENV"] = genv["ENV"]

env["CFLAGS"] += [
    "-O3",
    "-g",
    "-Wno-unused-value",
    "-Wno-unused-parameter",
    "-D_GNU_SOURCE",
]

env["LIBPATH"] = [
    genv["out"],
]

env["CCFLAGS"] = [
    "-O3",
    "-g",
    "-Wno-unused-value",
    "-Wno-unused-parameter",
    "-D_GNU_SOURCE",
]

env["LINKFLAGS"] = [
]

dst = "s5-proxy"

inc = [
    "#tests",
    ".",
    "../../include",
]

src = [
    "client.c",
    "getopt.c",
    "main.c",
    "s5.c",
    "server.c",
    "util.c",
]

lib = [
    "uv",
    "pthread",
]

sample_prog = env.Program(target=dst, source=src, LIBS=lib, CPPPATH=inc)
Return("sample_prog")
